spring:
  application:
    name: Pastebin
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 787898
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    session:
      tracking-modes: cookie
  storage:
    folder-id: 16HtRVAC-5aU2-RUu15XrNH7fc_wyrbSS
    main-path: https://drive.google.com/uc?export=view&id=
  mail:
    host: smtp.gmail.com
    port: 587
    username: nikitalazurcenko@gmail.com
    password: emdg ktel sger lncu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
